from pygments.token import Token

TOKENS = [
    (Token.Punctuation, "<"),
    (Token.Name.Tag, "template"),
    (Token.Punctuation, ">"),
    (Token.Text, "\n  "),
    (Token.Punctuation, "<"),
    (Token.Name.Tag, "div"),
    (Token.Text, " "),
    (Token.Name.Attribute, "class"),
    (Token.Operator, "="),
    (Token.Literal.String, '"container"'),
    (Token.Punctuation, ">"),
    (Token.Text, "\n    "),
    (Token.Punctuation, "<"),
    (Token.Name.Tag, "button"),
    (Token.Text, " "),
    (Token.Name.Attribute, "type"),
    (Token.Operator, "="),
    (Token.Literal.String, '"button"'),
    (Token.Text, " "),
    (Token.Name.Attribute, "class"),
    (Token.Operator, "="),
    (Token.Literal.String, '"btn btn-primary"'),
    (Token.Punctuation, ">"),
    (Token.Punctuation, "{"),
    (Token.Punctuation, "{"),
    (Token.Text, " "),
    (Token.Name.Other, "msg"),
    (Token.Text, " "),
    (Token.Punctuation, "}"),
    (Token.Punctuation, "}"),
    (Token.Punctuation, "<"),
    (Token.Punctuation, "/"),
    (Token.Name.Tag, "button"),
    (Token.Punctuation, ">"),
    (Token.Text, "\n  "),
    (Token.Punctuation, "<"),
    (Token.Punctuation, "/"),
    (Token.Name.Tag, "div"),
    (Token.Punctuation, ">"),
    (Token.Text, "\n"),
    (Token.Punctuation, "<"),
    (Token.Punctuation, "/"),
    (Token.Name.Tag, "template"),
    (Token.Punctuation, ">"),
    (Token.Text, "\n\n"),
    (Token.Punctuation, "<"),
    (Token.Name.Tag, "script"),
    (Token.Punctuation, ">"),
    (Token.Text, "\n  "),
    (Token.Keyword.Reserved, "export"),
    (Token.Text, " "),
    (Token.Keyword, "default"),
    (Token.Text, " "),
    (Token.Punctuation, "{"),
    (Token.Text, "\n    "),
    (Token.Name.Other, "name"),
    (Token.Operator, ":"),
    (Token.Text, " "),
    (Token.Literal.String.Single, "'Ping'"),
    (Token.Punctuation, ","),
    (Token.Text, "\n    "),
    (Token.Name.Other, "data"),
    (Token.Punctuation, "("),
    (Token.Punctuation, ")"),
    (Token.Text, " "),
    (Token.Punctuation, "{"),
    (Token.Text, "\n      "),
    (Token.Keyword, "return"),
    (Token.Text, " "),
    (Token.Punctuation, "{"),
    (Token.Text, "\n        "),
    (Token.Name.Other, "msg"),
    (Token.Operator, ":"),
    (Token.Text, " "),
    (Token.Literal.String.Single, "''"),
    (Token.Punctuation, ","),
    (Token.Text, "\n      "),
    (Token.Punctuation, "}"),
    (Token.Punctuation, ";"),
    (Token.Text, "\n    "),
    (Token.Punctuation, "}"),
    (Token.Punctuation, ","),
    (Token.Text, "\n    "),
    (Token.Name.Other, "methods"),
    (Token.Operator, ":"),
    (Token.Text, " "),
    (Token.Punctuation, "{"),
    (Token.Text, "\n      "),
    (Token.Name.Other, "getMessage"),
    (Token.Punctuation, "("),
    (Token.Punctuation, ")"),
    (Token.Text, " "),
    (Token.Punctuation, "{"),
    (Token.Text, "\n        "),
    (Token.Keyword, "this"),
    (Token.Punctuation, "."),
    (Token.Name.Other, "msg"),
    (Token.Text, " "),
    (Token.Operator, "="),
    (Token.Text, " "),
    (Token.Literal.String.Single, "'Pong'"),
    (Token.Punctuation, ";"),
    (Token.Text, "\n      "),
    (Token.Punctuation, "}"),
    (Token.Punctuation, ","),
    (Token.Text, "\n    "),
    (Token.Punctuation, "}"),
    (Token.Punctuation, ","),
    (Token.Text, "\n    "),
    (Token.Name.Other, "created"),
    (Token.Punctuation, "("),
    (Token.Punctuation, ")"),
    (Token.Text, " "),
    (Token.Punctuation, "{"),
    (Token.Text, "\n      "),
    (Token.Keyword, "this"),
    (Token.Punctuation, "."),
    (Token.Name.Other, "getMessage"),
    (Token.Punctuation, "("),
    (Token.Punctuation, ")"),
    (Token.Punctuation, ";"),
    (Token.Text, "\n    "),
    (Token.Punctuation, "}"),
    (Token.Punctuation, ","),
    (Token.Text, "\n  "),
    (Token.Punctuation, "}"),
    (Token.Punctuation, ";"),
    (Token.Text, "\n"),
    (Token.Punctuation, "<"),
    (Token.Punctuation, "/"),
    (Token.Name.Tag, "script"),
    (Token.Punctuation, ">"),
    (Token.Text, "\n"),
]
